M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date 2024年07月29日 11時47分02秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-29T11:47:02+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.0392Y-1.9167
X6.0392Y-2.1592
T2
X5.149Y-2.9073
T0
M30
